# Exported from Render on 2025-05-28T12:00:26Z
services:
- type: web
  name: Test
  runtime: python
  repo: https://github.com/Punitkanzariya/Test
  plan: free
  envVars:
  - key: PUNIT
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn unit_converter_project.wsgi:application --bind 0.0.0.0:$PORT
  domains:
  - www.converterbypunitkanzariya
  - www.converterbypunit
  autoDeployTrigger: commit
version: "1"
